spring.application.name=InventoryApp

server.port=8080

# Database Connection (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/school_inventory?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=020407_Vili
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

# i18n
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Upload Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
